# -*- coding: utf-8 -*-
"""app

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1apO9faVBNeG07xxygr7b0IqUQ-RHzJTO
"""

"""
Streamlit Dashboard for Colab Notebook Manager
Displays all analyzed notebooks with AI-generated insights
"""

import streamlit as st
import sqlite3
import pandas as pd
import json
import plotly.express as px
import plotly.graph_objects as go
from datetime import datetime
import subprocess
import os

# Page config
st.set_page_config(
    page_title="🤖 AI Colab Manager",
    page_icon="🤖",
    layout="wide",
    initial_sidebar_state="expanded"
)

# Custom CSS
st.markdown("""
<style>
    .main-header {
        font-size: 3rem;
        font-weight: bold;
        background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
        -webkit-background-clip: text;
        -webkit-text-fill-color: transparent;
        text-align: center;
        margin-bottom: 1rem;
    }
    .notebook-card {
        border: 2px solid #e0e0e0;
        border-radius: 15px;
        padding: 20px;
        margin: 15px 0;
        background: linear-gradient(135deg, #f5f7fa 0%, #c3cfe2 100%);
        transition: all 0.3s;
        cursor: pointer;
    }
    .notebook-card:hover {
        transform: translateY(-5px);
        box-shadow: 0 10px 20px rgba(0,0,0,0.2);
    }
    .tag {
        background: #667eea;
        color: white;
        padding: 5px 12px;
        border-radius: 20px;
        margin: 3px;
        display: inline-block;
        font-size: 0.85rem;
    }
    .metric-box {
        background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
        color: white;
        padding: 25px;
        border-radius: 15px;
        text-align: center;
        box-shadow: 0 5px 15px rgba(0,0,0,0.2);
    }
    .open-btn {
        background: #667eea;
        color: white;
        padding: 10px 20px;
        border-radius: 25px;
        text-decoration: none;
        display: inline-block;
        margin-top: 10px;
    }
    .open-btn:hover {
        background: #764ba2;
        color: white;
        text-decoration: none;
    }
</style>
""", unsafe_allow_html=True)

class NotebookDatabase:
    def __init__(self, db_path='database.db'):
        self.db_path = db_path

    def get_all_notebooks(self):
        """Get all notebooks from database"""
        conn = sqlite3.connect(self.db_path)
        query = "SELECT * FROM notebooks ORDER BY modified_time DESC"
        df = pd.read_sql_query(query, conn)
        conn.close()
        return df

    def get_statistics(self):
        """Get summary statistics"""
        conn = sqlite3.connect(self.db_path)
        cursor = conn.cursor()

        stats = {}

        # Total notebooks
        cursor.execute("SELECT COUNT(*) FROM notebooks")
        stats['total'] = cursor.fetchone()[0]

        # Analyzed notebooks
        cursor.execute("SELECT COUNT(*) FROM notebooks WHERE analyzed = 1")
        stats['analyzed'] = cursor.fetchone()[0]

        # By category
        cursor.execute("""
            SELECT category, COUNT(*) as count
            FROM notebooks
            WHERE category IS NOT NULL
            GROUP BY category
        """)
        stats['by_category'] = dict(cursor.fetchall())

        # Total code lines
        cursor.execute("SELECT SUM(total_code_lines) FROM notebooks")
        stats['total_lines'] = cursor.fetchone()[0] or 0

        conn.close()
        return stats

    def search_notebooks(self, search_term):
        """Search notebooks by name, summary, or tags"""
        conn = sqlite3.connect(self.db_path)
        query = f"""
            SELECT * FROM notebooks
            WHERE name LIKE '%{search_term}%'
            OR summary LIKE '%{search_term}%'
            OR tags LIKE '%{search_term}%'
            OR category LIKE '%{search_term}%'
            ORDER BY modified_time DESC
        """
        df = pd.read_sql_query(query, conn)
        conn.close()
        return df

def display_notebook_card(notebook):
    """Display a beautiful notebook card"""
    tags = json.loads(notebook['tags']) if notebook['tags'] else []
    tags_html = "".join([f"<span class='tag'>{tag}</span>" for tag in tags])

    st.markdown(f"""
    <div class='notebook-card'>
        <h3>📓 {notebook['name']}</h3>
        <p><strong>📁 Account:</strong> {notebook['account']}</p>
        <p><strong>🎯 Category:</strong> {notebook['category'] or 'Uncategorized'}</p>
        <p><strong>📝 Summary:</strong> {notebook['summary'] or 'Not analyzed yet'}</p>
        <p><strong>🎯 Main Goal:</strong> {notebook['main_goal'] or 'Not specified'}</p>
        <p><strong>💡 Key Findings:</strong> {notebook['key_findings'] or 'N/A'}</p>
        <p><strong>📊 Lines of Code:</strong> {notebook['total_code_lines']}</p>
        <p><strong>🏷️ Tags:</strong><br>{tags_html}</p>
        <p><small>🕒 Last Modified: {notebook['modified_time'][:10] if notebook['modified_time'] else 'Unknown'}</small></p>
    </div>
    """, unsafe_allow_html=True)

    # Open button
    col1, col2 = st.columns(2)
    with col1:
        st.link_button("🚀 Open in Colab", notebook['colab_link'], use_container_width=True)
    with col2:
        st.link_button("📂 Open in Drive", notebook['web_link'], use_container_width=True)

def main():
    st.markdown("<h1 class='main-header'>🤖 AI-Powered Colab Manager</h1>", unsafe_allow_html=True)

    db = NotebookDatabase()

    # Sidebar
    with st.sidebar:
        st.image("https://www.gstatic.com/colaboratory/assets/colab-logo.svg", width=150)
        st.title("⚙️ Control Panel")

        st.markdown("---")

        # Scan button
        if st.button("🔄 Scan Drive for Notebooks", use_container_width=True):
            with st.spinner("Scanning Google Drive..."):
                try:
                    subprocess.run(["python", "scanner.py"], check=True)
                    st.success("✅ Scan complete!")
                    st.rerun()
                except Exception as e:
                    st.error(f"Error: {e}")

        # Analyze button
        if st.button("🧠 Analyze with AI", use_container_width=True):
            with st.spinner("Analyzing notebooks with AI..."):
                try:
                    subprocess.run(["python", "agent.py"], check=True)
                    st.success("✅ Analysis complete!")
                    st.rerun()
                except Exception as e:
                    st.error(f"Error: {e}")

        st.markdown("---")

        # Navigation
        page = st.radio(
            "Navigate to:",
            ["🏠 Dashboard", "📚 All Notebooks", "🔍 Search", "📊 Analytics", "⚙️ Settings"],
            label_visibility="collapsed"
        )

        st.markdown("---")

        # Stats
        stats = db.get_statistics()
        st.metric("Total Notebooks", stats['total'])
        st.metric("Analyzed", stats['analyzed'])
        st.metric("Total Code Lines", f"{stats['total_lines']:,}")

    # Main content
    if page == "🏠 Dashboard":
        show_dashboard(db)
    elif page == "📚 All Notebooks":
        show_all_notebooks(db)
    elif page == "🔍 Search":
        show_search(db)
    elif page == "📊 Analytics":
        show_analytics(db)
    elif page == "⚙️ Settings":
        show_settings()

def show_dashboard(db):
    """Main dashboard"""
    st.header("📊 Dashboard Overview")

    stats = db.get_statistics()

    # Metrics
    col1, col2, col3, col4 = st.columns(4)

    with col1:
        st.markdown(f"""
        <div class='metric-box'>
            <h2>{stats['total']}</h2>
            <p>Total Notebooks</p>
        </div>
        """, unsafe_allow_html=True)

    with col2:
        st.markdown(f"""
        <div class='metric-box'>
            <h2>{stats['analyzed']}</h2>
            <p>AI Analyzed</p>
        </div>
        """, unsafe_allow_html=True)

    with col3:
        pending = stats['total'] - stats['analyzed']
        st.markdown(f"""
        <div class='metric-box'>
            <h2>{pending}</h2>
            <p>Pending Analysis</p>
        </div>
        """, unsafe_allow_html=True)

    with col4:
        st.markdown(f"""
        <div class='metric-box'>
            <h2>{stats['total_lines']:,}</h2>
            <p>Lines of Code</p>
        </div>
        """, unsafe_allow_html=True)

    st.markdown("---")

    # Recent notebooks
    st.subheader("🕒 Recently Modified")

    df = db.get_all_notebooks()

    if not df.empty:
        recent = df.head(6)

        for _, nb in recent.iterrows():
            display_notebook_card(nb)
    else:
        st.info("👆 Click 'Scan Drive' in the sidebar to get started!")

def show_all_notebooks(db):
    """Show all notebooks with filters"""
    st.header("📚 All Notebooks")

    df = db.get_all_notebooks()

    if df.empty:
        st.warning("No notebooks found. Click 'Scan Drive' in the sidebar.")
        return

    # Filters
    col1, col2, col3 = st.columns(3)

    with col1:
        categories = ['All'] + sorted(df['category'].dropna().unique().tolist())
        selected_cat = st.selectbox("📁 Category", categories)

    with col2:
        accounts = ['All'] + sorted(df['account'].unique().tolist())
        selected_account = st.selectbox("👤 Account", accounts)

    with col3:
        sort_by = st.selectbox("🔀 Sort by", ["Recent", "Name", "Size"])

    # Filter
    filtered = df.copy()

    if selected_cat != 'All':
        filtered = filtered[filtered['category'] == selected_cat]

    if selected_account != 'All':
        filtered = filtered[filtered['account'] == selected_account]

    # Sort
    if sort_by == "Recent":
        filtered = filtered.sort_values('modified_time', ascending=False)
    elif sort_by == "Name":
        filtered = filtered.sort_values('name')
    elif sort_by == "Size":
        filtered = filtered.sort_values('total_code_lines', ascending=False)

    st.info(f"Showing {len(filtered)} of {len(df)} notebooks")

    # Display
    for _, nb in filtered.iterrows():
        display_notebook_card(nb)

def show_search(db):
    """Search functionality"""
    st.header("🔍 Search Notebooks")

    search_term = st.text_input(
        "Search by name, summary, tags, or category",
        placeholder="e.g., 'machine learning', 'tensorflow', 'image classification'..."
    )

    if search_term:
        results = db.search_notebooks(search_term)

        st.success(f"Found {len(results)} results for '{search_term}'")

        for _, nb in results.iterrows():
            display_notebook_card(nb)
    else:
        st.info("👆 Enter a search term to find notebooks")

def show_analytics(db):
    """Analytics page"""
    st.header("📊 Analytics & Insights")

    df = db.get_all_notebooks()

    if df.empty:
        st.warning("No data available")
        return

    # Category distribution
    st.subheader("📂 Notebooks by Category")

    category_counts = df['category'].value_counts()

    fig = px.pie(
        values=category_counts.values,
        names=category_counts.index,
        title="Distribution by Category",
        color_discrete_sequence=px.colors.sequential.Purples
    )
    st.plotly_chart(fig, use_container_width=True)

    # Timeline
    st.subheader("📈 Creation Timeline")

    df['created_date'] = pd.to_datetime(df['created_time']).dt.date
    timeline = df.groupby('created_date').size().reset_index(name='count')

    fig = px.line(
        timeline,
        x='created_date',
        y='count',
        title="Notebooks Created Over Time"
    )
    st.plotly_chart(fig, use_container_width=True)

    # Account distribution
    col1, col2 = st.columns(2)

    with col1:
        st.subheader("👤 By Account")
        account_counts = df['account'].value_counts()
        fig = px.bar(
            x=account_counts.index,
            y=account_counts.values,
            labels={'x': 'Account', 'y': 'Count'}
        )
        st.plotly_chart(fig, use_container_width=True)

    with col2:
        st.subheader("📊 Code Size Distribution")
        fig = px.histogram(
            df,
            x='total_code_lines',
            nbins=20,
            title="Lines of Code Distribution"
        )
        st.plotly_chart(fig, use_container_width=True)

    # Popular tags
    st.subheader("🏷️ Most Used Tags")

    all_tags = []
    for tags_str in df['tags'].dropna():
        try:
            tags = json.loads(tags_str)
            all_tags.extend(tags)
        except:
            pass

    if all_tags:
        tag_counts = pd.Series(all_tags).value_counts().head(20)

        fig = px.bar(
            x=tag_counts.values,
            y=tag_counts.index,
            orientation='h',
            title="Top 20 Tags",
            labels={'x': 'Count', 'y': 'Tag'}
        )
        st.plotly_chart(fig, use_container_width=True)

def show_settings():
    """Settings page"""
    st.header("⚙️ Settings")

    st.subheader("🔑 API Configuration")

    # Check if API key is set
    if os.getenv('GEMINI_API_KEY'):
        st.success("✅ Gemini API Key configured")
    else:
        st.error("❌ Gemini API Key not found")
        st.info("Add your API key to the .env file")

    st.subheader("📂 Google Drive Accounts")

    # Check for token files
    if os.path.exists('token_Account1.pickle'):
        st.success("✅ Account 1 authenticated")
    else:
        st.warning("⚠️ Account 1 not authenticated")

    if os.path.exists('token_Account2.pickle'):
        st.success("✅ Account 2 authenticated")
    else:
        st.info("ℹ️ Account 2 not configured")

    st.subheader("🗄️ Database Info")

    if os.path.exists('database.db'):
        size = os.path.getsize('database.db') / 1024 / 1024
        st.info(f"Database size: {size:.2f} MB")
    else:
        st.warning("Database not created yet")

    st.subheader("🔄 Automation")

    st.info("💡 Set up automatic scanning with cron jobs or Task Scheduler")

    code = """
# Linux/Mac (crontab -e):
0 */6 * * * cd /path/to/colab-analyzer && python scanner.py && python agent.py

# Windows (Task Scheduler):
# Create a batch file that runs both scripts
"""
    st.code(code, language="bash")

if __name__ == "__main__":
    main()